import type { Metadata } from "next";
import { Playfair_Display, Clicker_Script } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-playfair",
});

const clicker = Clicker_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-clicker",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${clicker.variable}`}>
      <body>{children}</body>
    </html>
  );
}
